name: scriby_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: 8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  shared_preferences: ^2.2.3
  talker_flutter: ^4.3.4
  auto_route: ^8.2.0
  realm: ^3.3.0
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  uuid: ^4.4.2
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.11
  auto_route_generator: 8.0.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product Sans 400.ttf
        - asset: assets/fonts/Product Sans Bold 700.ttf